// AUTO-GENERATED by scripts/gen-sa-fleet.js from the loopd derived fleet feed. DO NOT EDIT BY HAND.
// Regenerate: node scripts/gen-sa-fleet.js   (source: loopd seed-fleet-graph -> fleet-map -> fleet-derive-local)
// Every value below is roster (owner-declared) + facts derived from the real git repos — never hand-typed.
export interface SANode { id: string; label: string; cat: string; tagline: string; present: boolean; version: string | null; status: string; commits_since_tag: number | null; last_commit: string | null; mcp: boolean; awaiting: boolean; planes: string[]; }
export interface SACat { id: string; label: string; color: string; count: number; }
export interface SAFleet { generated: string; derived_at: string | null; stats: { nodes: number; present: number; tagged: number; mcp: number; awaiting: number; edges: number }; cats: SACat[]; nodes: SANode[]; }

export const SA_FLEET: SAFleet = {
  "generated": "2026-06-25",
  "derived_at": "2026-06-25T01:13:20Z",
  "stats": {
    "nodes": 42,
    "present": 42,
    "tagged": 24,
    "mcp": 24,
    "awaiting": 5,
    "edges": 72
  },
  "cats": [
    {
      "id": "offensive",
      "label": "Offensive",
      "color": "#ff5a52",
      "count": 14
    },
    {
      "id": "defensive",
      "label": "Defensive",
      "color": "#4d9bff",
      "count": 3
    },
    {
      "id": "infra",
      "label": "Infrastructure",
      "color": "#34d3a6",
      "count": 6
    },
    {
      "id": "sensor",
      "label": "Sensor",
      "color": "#88ddff",
      "count": 1
    },
    {
      "id": "aiml",
      "label": "AI / ML",
      "color": "#aa66ff",
      "count": 2
    },
    {
      "id": "orchestration",
      "label": "Orchestration",
      "color": "#ffd23f",
      "count": 1
    },
    {
      "id": "authority",
      "label": "Authority",
      "color": "#ff8c2e",
      "count": 2
    },
    {
      "id": "agent",
      "label": "Agent",
      "color": "#22ccaa",
      "count": 9
    },
    {
      "id": "surface",
      "label": "Surface",
      "color": "#66aaff",
      "count": 4
    }
  ],
  "nodes": [
    {
      "id": "hog",
      "label": "HOG",
      "cat": "offensive",
      "tagline": "AI-augmented C2 / pentest orchestration",
      "present": true,
      "version": "v1.1.0-rc.1",
      "status": "v1.1.0-rc.1 · +18 since tag",
      "commits_since_tag": 18,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "marshald",
      "label": "Marshald",
      "cat": "orchestration",
      "tagline": "Fleet orchestration daemon",
      "present": true,
      "version": "v0.3.0",
      "status": "v0.3.0 · +10 since tag",
      "commits_since_tag": 10,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "aegis",
      "label": "Aegis",
      "cat": "defensive",
      "tagline": "Agentic IDS via cadence analysis",
      "present": true,
      "version": null,
      "status": "untagged · 39 commits",
      "commits_since_tag": null,
      "last_commit": "2026-04-04",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "sentinel",
      "label": "Sentinel",
      "cat": "defensive",
      "tagline": "eBPF-based host security monitoring",
      "present": true,
      "version": "v1.0.0",
      "status": "v1.0.0 · +1 since tag",
      "commits_since_tag": 1,
      "last_commit": "2026-06-22",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "phantom",
      "label": "Phantom",
      "cat": "offensive",
      "tagline": "LLM-powered vulnerability discovery",
      "present": true,
      "version": "v3.0.0",
      "status": "v3.0.0 · +1 since tag",
      "commits_since_tag": 1,
      "last_commit": "2026-06-21",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "malscope",
      "label": "Malscope",
      "cat": "defensive",
      "tagline": "AI-powered malware analysis sandbox",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +3 since tag",
      "commits_since_tag": 3,
      "last_commit": "2026-03-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "syscalld",
      "label": "eBPF Sensors",
      "cat": "sensor",
      "tagline": "Shared kernel-level telemetry",
      "present": true,
      "version": null,
      "status": "untagged · 26 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-20",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "de-voidlink",
      "label": "DE-VoidLink",
      "cat": "offensive",
      "tagline": "Local adversary simulation — detection engineering",
      "present": true,
      "version": null,
      "status": "untagged · 11 commits",
      "commits_since_tag": null,
      "last_commit": "2026-04-02",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "burrow",
      "label": "Burrow",
      "cat": "offensive",
      "tagline": "Advanced network pivoting tool",
      "present": true,
      "version": "v4.2.0-rc1",
      "status": "v4.2.0-rc1 · current",
      "commits_since_tag": 0,
      "last_commit": "2026-06-20",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "feedback",
      "label": "Feedback",
      "cat": "offensive",
      "tagline": "Covert LLM output exfiltration",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +1 since tag",
      "commits_since_tag": 1,
      "last_commit": "2026-03-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "fester",
      "label": "Fester",
      "cat": "offensive",
      "tagline": "Targeted dataset poisoning engine",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +4 since tag",
      "commits_since_tag": 4,
      "last_commit": "2026-04-03",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "grip",
      "label": "Grip",
      "cat": "infra",
      "tagline": "Cross-platform encrypted file sync",
      "present": true,
      "version": "rc-final.1",
      "status": "rc-final.1 · +8 since tag",
      "commits_since_tag": 8,
      "last_commit": "2026-06-24",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "vibe",
      "label": "Vibe",
      "cat": "infra",
      "tagline": "AI-Powered Electron IDE — Fleet Loop-Execution Agent",
      "present": true,
      "version": "v1.1.0-rc.2",
      "status": "v1.1.0-rc.2 · +5 since tag",
      "commits_since_tag": 5,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "mojodojo",
      "label": "Mojodojo",
      "cat": "aiml",
      "tagline": "AI model training & benchmarking",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +51 since tag",
      "commits_since_tag": 51,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "lamprey",
      "label": "Lamprey",
      "cat": "offensive",
      "tagline": "Real-time network traffic analysis",
      "present": true,
      "version": null,
      "status": "untagged · 38 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-21",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "glass",
      "label": "Glass",
      "cat": "infra",
      "tagline": "Privacy suite — TLS fingerprinting",
      "present": true,
      "version": "v1.0.0",
      "status": "v1.0.0 · +208 since tag",
      "commits_since_tag": 208,
      "last_commit": "2026-06-21",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "dossier",
      "label": "Dossier",
      "cat": "offensive",
      "tagline": "AI-powered OSINT intelligence",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +3 since tag",
      "commits_since_tag": 3,
      "last_commit": "2026-04-04",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product",
        "control-plane"
      ]
    },
    {
      "id": "fenrir",
      "label": "Fenrir",
      "cat": "offensive",
      "tagline": "BH CE v6 attack path scoring + engagement enrichment",
      "present": true,
      "version": "v9.1.0",
      "status": "v9.1.0 · +29 since tag",
      "commits_since_tag": 29,
      "last_commit": "2026-06-24",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "report-ng",
      "label": "Report-NG",
      "cat": "infra",
      "tagline": "Automated engagement report generation ← Sidekick",
      "present": true,
      "version": null,
      "status": "untagged · 48 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-24",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "cloudstrike",
      "label": "CloudStrike",
      "cat": "offensive",
      "tagline": "Cloud attack tooling",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +3 since tag",
      "commits_since_tag": 3,
      "last_commit": "2026-05-06",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "set-ng",
      "label": "SET-NG",
      "cat": "offensive",
      "tagline": "Social engineering toolkit",
      "present": true,
      "version": null,
      "status": "untagged · 15 commits",
      "commits_since_tag": null,
      "last_commit": "2026-03-22",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "mirage",
      "label": "Mirage",
      "cat": "aiml",
      "tagline": "Synthetic identity / deepfake engine",
      "present": true,
      "version": null,
      "status": "untagged · 44 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-22",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "product"
      ]
    },
    {
      "id": "darkwarden",
      "label": "darkwarden",
      "cat": "authority",
      "tagline": "Agent identity authority — sole credential minter + kill-switch",
      "present": true,
      "version": "v0.3.0-client.1",
      "status": "v0.3.0-client.1 · current",
      "commits_since_tag": 0,
      "last_commit": "2026-06-22",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "loopd",
      "label": "loopd",
      "cat": "authority",
      "tagline": "Fleet authority — declared truth + conformance verify",
      "present": true,
      "version": null,
      "status": "untagged · 30 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-24",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "sidekick",
      "label": "Sidekick",
      "cat": "agent",
      "tagline": "Pentest knowledge bus",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +22 since tag",
      "commits_since_tag": 22,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "athena",
      "label": "Athena",
      "cat": "agent",
      "tagline": "Wiki crawler & knowledge base agent",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +32 since tag",
      "commits_since_tag": 32,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "persistent-assistant",
      "label": "Persistent Assistant",
      "cat": "agent",
      "tagline": "Universal web/OSINT scraping daemon + CLI client agent",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +31 since tag",
      "commits_since_tag": 31,
      "last_commit": "2026-06-24",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "command-center",
      "label": "Command Center",
      "cat": "surface",
      "tagline": "Portal + State API control surface",
      "present": true,
      "version": null,
      "status": "untagged · 368 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-24",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "infragent-plugin",
      "label": "InfrAgent Plugin",
      "cat": "surface",
      "tagline": "Remote control-plane surface (mobile) — alongside Vibe",
      "present": true,
      "version": null,
      "status": "untagged · 14 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-23",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "grimoire",
      "label": "Grimoire",
      "cat": "surface",
      "tagline": "Markdown notes app host (hosts InfrAgent plugin)",
      "present": true,
      "version": "v1.2.0",
      "status": "v1.2.0 · +6 since tag",
      "commits_since_tag": 6,
      "last_commit": "2026-06-24",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "pry",
      "label": "Pry",
      "cat": "agent",
      "tagline": "Web testing proxy + most-integrated tool agent",
      "present": true,
      "version": "rc-v1",
      "status": "rc-v1 · +2 since tag",
      "commits_since_tag": 2,
      "last_commit": "2026-06-22",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "wraith",
      "label": "WRAITH",
      "cat": "agent",
      "tagline": "AI testing C2 (original Hand-of-God)",
      "present": true,
      "version": null,
      "status": "untagged · 36 commits",
      "commits_since_tag": null,
      "last_commit": "2026-05-23",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "trusted",
      "label": "Trusted",
      "cat": "agent",
      "tagline": "ADCS/PKI + cert-auth C2",
      "present": true,
      "version": "release-ready-20260615",
      "status": "release-ready-20260615 · +3 since tag",
      "commits_since_tag": 3,
      "last_commit": "2026-06-23",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "purpsquad",
      "label": "PurpSquad",
      "cat": "agent",
      "tagline": "Purple-team simulator",
      "present": true,
      "version": null,
      "status": "untagged · 4 commits",
      "commits_since_tag": null,
      "last_commit": "2026-03-13",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "scry",
      "label": "Scry",
      "cat": "agent",
      "tagline": "TLS/SSL assessment & divination",
      "present": true,
      "version": null,
      "status": "untagged · 33 commits",
      "commits_since_tag": null,
      "last_commit": "2026-06-23",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "crack-ng",
      "label": "crack-ng",
      "cat": "agent",
      "tagline": "Hash-cracking orchestrator (Rust)",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +26 since tag",
      "commits_since_tag": 26,
      "last_commit": "2026-04-05",
      "mcp": false,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "artemis",
      "label": "Artemis",
      "cat": "surface",
      "tagline": "Dashboard/control plane for Bjorn/pwnagotchi companions",
      "present": true,
      "version": null,
      "status": "untagged · 5 commits",
      "commits_since_tag": null,
      "last_commit": "2026-03-13",
      "mcp": true,
      "awaiting": false,
      "planes": [
        "control-plane"
      ]
    },
    {
      "id": "bjornagotchi",
      "label": "Bjornagotchi",
      "cat": "offensive",
      "tagline": "Agentified pwnagotchi/Bjorn RPi-zero redteam devices",
      "present": true,
      "version": null,
      "status": "untagged · 7 commits",
      "commits_since_tag": null,
      "last_commit": "2026-03-25",
      "mcp": false,
      "awaiting": true,
      "planes": [
        "awaiting"
      ]
    },
    {
      "id": "anvil",
      "label": "Anvil",
      "cat": "offensive",
      "tagline": "Payload build/obfuscation generator",
      "present": true,
      "version": null,
      "status": "untagged · 5 commits",
      "commits_since_tag": null,
      "last_commit": "2026-04-05",
      "mcp": false,
      "awaiting": true,
      "planes": [
        "awaiting"
      ]
    },
    {
      "id": "cvedb",
      "label": "cvedb",
      "cat": "infra",
      "tagline": "Dynamic CVE data feed",
      "present": true,
      "version": null,
      "status": "untagged · 3 commits",
      "commits_since_tag": null,
      "last_commit": "2026-03-21",
      "mcp": false,
      "awaiting": true,
      "planes": [
        "awaiting"
      ]
    },
    {
      "id": "i2p-utils",
      "label": "i2p-utils",
      "cat": "infra",
      "tagline": "Drop-in I2P connection manager",
      "present": true,
      "version": null,
      "status": "untagged · 5 commits",
      "commits_since_tag": null,
      "last_commit": "2026-03-30",
      "mcp": false,
      "awaiting": true,
      "planes": [
        "awaiting"
      ]
    },
    {
      "id": "courier",
      "label": "Courier",
      "cat": "offensive",
      "tagline": "Phishing & email security",
      "present": true,
      "version": "v1.0.0-rc.1",
      "status": "v1.0.0-rc.1 · +2 since tag",
      "commits_since_tag": 2,
      "last_commit": "2026-03-22",
      "mcp": false,
      "awaiting": true,
      "planes": [
        "awaiting"
      ]
    }
  ]
};
